In [ ]:
# Ejericcio 1
Obtener versión y configuración numpy

In [2]:
import numpy as np
np.__version__

'1.22.2'

# Ejercicio 2
Obtener información de la funcción add de numpy

In [2]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# Ejericio 3

Comprobar si un arreglo tiene elementos igual a cero 

In [6]:
Ejercicio3 = list(range(10))

Ejercicio3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
# El metodo all comprueba si uno de los elementos es igual a 0
np.all(Ejercicio3)

False

# Ejercico 4

Comprobar si un arreglo existe al menos un elemento distintos de cero

In [10]:
ejercicio4 = np.array((0, 0, 1, 0))

ejercicio4

array([0, 0, 1, 0])

In [12]:
# El metodo any que permite comprobar si al menos un elemento de la serie es distinto de cero

np.any(ejercicio4)

True

# Ejercicio 5
Comprobar si los elementos de un arreglo son finitos 

In [13]:
ejercicio5 = [0, 1, 2, 3, np.nan, np.inf, -np.inf]

ejercicio5

[0, 1, 2, 3, nan, inf, -inf]

In [15]:
# El metodo .isfinite comprueba elemento a elemento de un arreglo si los elementos corresponden con valores null o valores infinitos

np.isfinite(ejercicio5)

array([ True,  True,  True,  True, False, False, False])

# Ejercicio 7
Comprobar si los Elementos de un arreglo numpy son nulos

In [4]:
ej7 = np.array([2, 3, 5, np.nan, 8, np.nan])

ej7

array([ 2.,  3.,  5., nan,  8., nan])

In [5]:
np.isnan(ej7)

array([False, False, False,  True, False,  True])

# Ejercicio 8
Comprobar si cada elemento de un arreglo es un numero real, complejo o escalar

In [9]:
ej8 = np.array([1, -4j, 8, 6j])

In [10]:
np.iscomplex(ej8)

array([False,  True, False,  True])

In [11]:
np.isreal(ej8)

array([ True, False,  True, False])

In [14]:
np.isscalar(ej8)

False

# Ejercicio 9

Comprobar si dos arreglos son iguales bajo un grado de tolerancia 

In [15]:
np.allclose([1e10, 1e-7], [1.00001, 1e-8])

False