In [2]:
# Ejericcio 1
Obtener versión y configuración numpy

SyntaxError: invalid syntax (1394364988.py, line 2)

In [2]:
import numpy as np
np.__version__

'1.22.2'

# Ejercicio 2
Obtener información de la funcción add de numpy

In [2]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# Ejericio 3

Comprobar si un arreglo tiene elementos igual a cero 

In [6]:
Ejercicio3 = list(range(10))

Ejercicio3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
# El metodo all comprueba si uno de los elementos es igual a 0
np.all(Ejercicio3)

False

# Ejercico 4

Comprobar si un arreglo existe al menos un elemento distintos de cero

In [10]:
ejercicio4 = np.array((0, 0, 1, 0))

ejercicio4

array([0, 0, 1, 0])

In [12]:
# El metodo any que permite comprobar si al menos un elemento de la serie es distinto de cero

np.any(ejercicio4)

True

# Ejercicio 5
Comprobar si los elementos de un arreglo son finitos 

In [13]:
ejercicio5 = [0, 1, 2, 3, np.nan, np.inf, -np.inf]

ejercicio5

[0, 1, 2, 3, nan, inf, -inf]

In [15]:
# El metodo .isfinite comprueba elemento a elemento de un arreglo si los elementos corresponden con valores null o valores infinitos

np.isfinite(ejercicio5)

array([ True,  True,  True,  True, False, False, False])

# Ejercicio 7
Comprobar si los Elementos de un arreglo numpy son nulos

In [4]:
ej7 = np.array([2, 3, 5, np.nan, 8, np.nan])

ej7

array([ 2.,  3.,  5., nan,  8., nan])

In [5]:
np.isnan(ej7)

array([False, False, False,  True, False,  True])

# Ejercicio 8
Comprobar si cada elemento de un arreglo es un numero real, complejo o escalar

In [9]:
ej8 = np.array([1, -4j, 8, 6j])

In [10]:
np.iscomplex(ej8)

array([False,  True, False,  True])

In [11]:
np.isreal(ej8)

array([ True, False,  True, False])

In [14]:
np.isscalar(ej8)

False

# Ejercicio 9

Comprobar si dos arreglos son iguales bajo un grado de tolerancia 

In [15]:
np.allclose([1e10, 1e-7], [1.00001, 1e-8])

False

# Ejercicio 10 
Aplicar operadores relacionales a cada elemento de dos arreglos 

In [16]:
ej10 = np.array([5, 7])

ej10b = np.array([4, 9])

In [18]:
np.less(ej10, ej10b)

array([False,  True])

In [19]:
np.less_equal(ej10, ej10b)

array([False,  True])

In [20]:
np.greater(ej10, ej10b)

array([ True, False])

In [21]:
np.greater_equal(ej10, ej10b)

array([ True, False])

# Ejercicio 13
Crear tres arreglos con 10 ceros, 10 unos y 10 sietes 


In [2]:
arreglo1 = np.zeros(10)

In [4]:
arreglo2 = np.ones(10)

In [3]:
arreglo3 = np.ones(10)* 7

# Ejercicio 14
Crear un arreglo con enteros entre 20 y 50

In [5]:
arreglo14 = np.arange(10, 51)

arreglo14

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# Arreglo 15
Crear un arreglo con enteros pares entre 20 y 50

In [7]:
arreglo15 = np.arange(20, 51, 2)

arreglo15

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

# Ejercicio 16

crear una matriz identidad 

In [9]:
matriz16 = np.identity(3)

matriz16

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Ejercicio 17
Generar un numero aleatorio entre 0 y 1

In [11]:
aleatorio17 = np.random.random()

aleatorio17

array([0.97438601, 0.72690347])

# Ejercicio 18
Generar 10 numeros aleatorios siguiendo una distribución normal estandar 

In [12]:
aleatorio18 = np.random.normal(0, 1, 10)

aleatorio18

array([-0.61397442,  0.58251832, -0.21311585, -1.56775256, -0.8454218 ,
        1.64949495,  0.57483644, -0.01748808, -0.23095718,  0.49010034])

# Ejercicio 19
Crear un rango de numeros y excluir el perimer y ultimo elemento

In [13]:
ejercicio19 = np.arange(15, 55)

ejercicio19

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

In [15]:
ejercicio19[5:-1]

ejercicio19

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

# Ejercicio 20 
Crear una matriz de 4x3 e imprimir su contenido

In [16]:
arreglo20 = np.arange(1, 13).reshape((4,3))

arreglo20

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
for elemento in np.nditer(arreglo20):
    print(elemento, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Ejercicio 21

Crear un arreglo con 5 valores distribuidos uniformente entre 10 y 50

In [6]:
arreglo21 = np.linspace(10, 50, 5)

arreglo21

array([10., 20., 30., 40., 50.])

# Ejercicio 22 
Crear un arreglo con valores 0 a 9, e invertir el signo de los valores 5 y 7

In [8]:
arreglo22 = np.arange(10)

arreglo22

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arreglo22[(arreglo22 >= 5) & (arreglo22 <= 7)]*= -1

arreglo22

array([ 0,  1,  2,  3,  4, -5, -6, -7,  8,  9])

# Ejercicio 23
Crear arreglo con 5 elementos con valores aleatorios 

In [14]:
arreglo23 = np.random.randint(0, 11, 5)

arreglo23

array([2, 2, 0, 0, 7])

# Ejercicio 24

Multiplicar elemento a elemento dos arreglos 

In [17]:
arreglo24A = np.array([1, 2, 3, 5])

arreglo24B = np.array([5, 6, 7, 8])

In [19]:
resultado24 = arreglo24A * arreglo24B

resultado24

array([ 5, 12, 21, 40])

# Ejercicio 25 
Crear una matriz de 3x4 con valores de 1 a 12

In [24]:
matriz25 = np.arange(1,13).reshape((3,4))

matriz25

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Ejercicio 26 

Obtener la cantidad de filas y columnas de una matriz

In [25]:
matriz26 = np.arange(1, 13).reshape((3, 4))

In [26]:
matriz26.shape

(3, 4)

# Ejercicio 27
Crea una matriz identidad 5x5

In [3]:
matriz27 = np.eye(5,5)

matriz27

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Ejercicio 28
Crear una matriz marco


In [5]:
matriz28 = np.ones((10, 10))

matriz28

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
matriz28[1:-1,1:-1] = 0

matriz28                        

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Ejercicio 29

Crear matriz de 5x5 con los valores 1 a 5 en la diagonal principal

In [9]:
m29 = np.diag([1, 2, 3, 4, 5])

m29

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Ejercicio 30 
Crear una matriz 4x4 con 0 y 1 escalonados

In [10]:
m30 = np.zeros((4,4))
m30

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
m30[::2, 1::2] = 1

m30

array([[0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [16]:
m30[::2, ::2] = 1

m30

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

# Ejercicio 31 
Crear un arreglo tridimensional con valores aleatorios 

In [2]:
a31 = np.random.random((3, 3, 3))
a31

array([[[0.79247425, 0.85857345, 0.82103131],
        [0.17092604, 0.09015758, 0.35306963],
        [0.49260761, 0.62185889, 0.27260048]],

       [[0.46560586, 0.59799298, 0.45390066],
        [0.99380761, 0.95404529, 0.2563106 ],
        [0.24438623, 0.82472433, 0.62788351]],

       [[0.97784738, 0.47538907, 0.69006132],
        [0.75623589, 0.96581807, 0.7249052 ],
        [0.38965823, 0.93858139, 0.934287  ]]])

# Ejercicio 32
Sumar todos los elementos de una matriz

In [5]:
m32 = np.array([[1,2,3], [4,5,6]])
m32

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.sum(m32)

21

# Ejercicio 33
Calcular el producto punto entre dos vectores 


In [7]:
a33 = np.array([3,5])
ab33 = np.array([2, 3])

a33 ,ab33

(array([3, 5]), array([2, 3]))

In [8]:
np.dot(a33, ab33)

21

# Ejercicio 34
Sumar un arreglo a cada fila de una matriz

In [9]:
a34 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]] )

In [ ]:
arreglo34 = np.array([1,1,0])

In [10]:
resultado34 = np.empty_like(a34)
resultado34

array([[     94009042813942,                   0,                   0],
       [                  0,        240518168576, 3760896222469252197],
       [3763095473388282934, 4122538791031747637, 3703705129442619953],
       [7378078410305187888, 3991086691207165234, 3907261016486196277]])

In [ ]:
for i in range(4):
    resultado[i, :] = m[i,:] +arreglo34

In [11]:
resultado34

array([[     94009042813942,                   0,                   0],
       [                  0,        240518168576, 3760896222469252197],
       [3763095473388282934, 4122538791031747637, 3703705129442619953],
       [7378078410305187888, 3991086691207165234, 3907261016486196277]])

# Ejercicio 41
Sumar, restar, multiplicar y dividir escalares


In [4]:
np.add(1,51)

52

In [6]:
np.subtract(54, 52)

2

In [7]:
np.multiply(5, 6)

30

In [8]:
np.divide(10,2)

5.0

# Ejercicio 42
calcular el logartimo de la suma de la exponenciacion

In [9]:
log42 = np.log(1e-30)
logb42 = np.log(2.5e-30)

In [10]:
np.logaddexp(log42, logb42)

-67.824789821326

In [11]:
np.logaddexp2(log42, logb42)

-67.54785336784101

# Ejercicio 43
Dividir cada elemento de un arreglo por un numero arbitrario 

In [12]:
arreglo43 = np.arange(10)
arreglo43

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.true_divide(arreglo43, 5)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

# Ejercicio 44
Dividir cada elemento de un arreglo por un numero concreto y redondear 

In [14]:
a44 = np.array([3,5,8])
a44

array([3, 5, 8])

In [15]:
np.floor_divide(a44, 2)

array([1, 2, 4])

# Ejercicio 45
Elevar a un numero arbitrario cada elemento de un arreglo

In [16]:
a45 = np.arange(7)
a45

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
np.power(a45, 3)

array([  0,   1,   8,  27,  64, 125, 216])

# Ejercicio 46
Calcular el residuo al dividir un arreglo entre un numero arbitrario 

In [18]:
np.remainder(a45, 3)

array([0, 1, 2, 0, 1, 2, 0])

# Ejercicio 47
Calcular el valor absoluto de un arreglo

In [19]:
a47 = ([1, -2, -5, -9, 10])

In [20]:
np.absolute(a47)

array([ 1,  2,  5,  9, 10])

# Ejercicio 48 
Redondear los elementos de un arreglo 

In [21]:
a48 = ([3.1416, 2.718281, 1.4166465847])

In [22]:
np.round(a48)

array([3., 3., 1.])

In [24]:
np.round(a48, decimals=2)

array([3.14, 2.72, 1.42])

# Ejercicio 49
Redondear los elementos de un arreglo al entero más cercano

In [25]:
np.rint(a48)

array([3., 3., 1.])

# Ejercicio 50
Redondear hacia bajo, arriba y truncar los elementos de un arreglo

In [26]:
np.floor(a48)

array([3., 2., 1.])

In [27]:
np.ceil(a48)

array([4., 3., 2.])

In [28]:
np.trunc(a48)

array([3., 2., 1.])

# Ejercicio 54
Calcular el producto cruz de dos vectores

In [13]:
x54 = np.array([1,2,3])
y54 = np.array([9,8,7])

In [15]:
np.cross(x54, y54)

array([-10,  20, -10])

# Ejercicio 55 
Apartir de dos arreglos crear una multiplicación de matrices

In [16]:
x55 = [[1,2], [3,4]]
y55 = [[4,5], [7,8]]

In [17]:
np.matmul(x55, y55)

array([[18, 21],
       [40, 47]])

# Ejercicio 57
Encontrar el valor de un polinomio para un x arbitro 

In [3]:
np.polyval([1,6,9],2)

25

# Ejercicio 58

Aplicar operaciones aritmeticas para polinomios 

In [4]:
coef_a58 = (5,10,20)
coef_b58 = (7,11, 14)

In [7]:
np.polynomial.polynomial.polyadd(coef_a58, coef_b58)

array([12., 21., 34.])

In [8]:
np.polynomial.polynomial.polysub(coef_a58, coef_b58)

array([-2., -1.,  6.])

In [9]:
np.polynomial.polynomial.polymul(coef_a58, coef_b58)

array([ 35., 125., 320., 360., 280.])

# Ejercicio 59

Calcular el promedio de una matriz por cada dimensión

In [13]:
matriz59 = np.array([[21,51],[58,51]])

In [14]:
matriz59.mean(axis=0)

array([39.5, 51. ])

In [15]:
matriz59.mean(axis=1)

array([36. , 54.5])

# Ejercicio 60
Calcular estadisticas basicas sobre un arreglo

In [16]:
a60 = np.arange(50)

In [18]:
a60.mean()


24.5

In [19]:
a60.std()

14.430869689661812

In [20]:
a60.var()

208.25

# Ejercicio 88
Encontrar la diferencia entre dos arreglos

In [2]:
a88 = np.array([2,1,15,-14,5,-17,10,-10])

ab88 = np.array([21,1,15,-154,5,-17,160,-10])

In [3]:
np.setdiff1d(a88, ab88)

array([-14,   2,  10])

# Ejercicio 89
Obtener los elementos unicos de dos arreglos

In [5]:
np.setxor1d(a88, ab88)

array([-154,  -14,    2,   10,   21,  160])

# Ejercicio 90

Encontrar la unión de dos arreglos

In [6]:
np.union1d(a88, ab88) 


array([-154,  -17,  -14,  -10,    1,    2,    5,   10,   15,   21,  160])

error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ef3c43d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))


# Ejercicio 92
Repetir los elementos de un arreglo 

In [9]:
an92 = np.tile(a88, 4)
an92

array([  2,   1,  15, -14,   5, -17,  10, -10,   2,   1,  15, -14,   5,
       -17,  10, -10,   2,   1,  15, -14,   5, -17,  10, -10,   2,   1,
        15, -14,   5, -17,  10, -10])

# Ejercicio 95
Usar operadores relacionales sobre dos arreglos 

In [6]:
a95 = np.array([1,2,3,4,5])
b95 = np.array([5,8,7,8,9])

In [7]:
np.greater_equal(a95, b95)

array([False, False, False, False, False])

In [8]:
np.greater(a95, b95)

array([False, False, False, False, False])

In [9]:
np.less(a95, b95)

array([ True,  True,  True,  True,  True])

In [10]:
np.less_equal(a95, b95)

array([ True,  True,  True,  True,  True])

# Ejercicio 96
Ordenar una matriz por filas y columnas 

In [11]:
a96 = np.array([[4,6,9],[9,5,10]])

In [12]:
np.sort(a96, axis=0)

array([[ 4,  5,  9],
       [ 9,  6, 10]])

In [13]:
np.sort(a96, axis=1)

array([[ 4,  6,  9],
       [ 5,  9, 10]])

# Ejercicio 97 
Ordenar un  grupo de appellido y nombres

In [14]:
nombres97 = ["jose","Noe","luis","Pinky"]
apellidos97 = ["Perez", "Ortiz","Aguilar","Chevez"]

In [17]:
np.lexsort((nombres97, apellidos97))

array([2, 3, 1, 0])

# Ejercicio 98
Crear un filtro sobre los elementos de un arreglo

In [18]:
a98 = np.array([6,1,47,18,15,9,0,17])

In [19]:
a98[a98 >10]

array([47, 18, 15, 17])

# Ejercicio 99 
Cambiar la dimension de un arreglo 



In [22]:
a98.shape

(8,)

In [27]:
a98.shape = (3,4)

ValueError: cannot reshape array of size 8 into shape (3,4)